In [3]:
import numpy as np

In [6]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [9]:
# maaking array of zeros
np.zeros(6)

#making array of ones
np.ones(6)

#making random array
np.empty(3, order='F')

#making array with range
cth = np.arange(5,10)
cth

array([5, 6, 7, 8, 9])

In [12]:
# appending 2 or more array
np.append(cth, [1,2])

# deleting element of array by index
np.delete(cth, 0)

# cth = np.append(cth, [1,2,10])
np.short(cth)

array([ 5,  6,  7,  8,  9,  1,  2, 10], dtype=int16)

In [13]:
#multii dimension array
array_example = np.array([
    [[0,1,2,3],
    [4,5,6,7]],
    [[0,1,2,3],
    [4,5,6,7]],
    [[0,1,2,3],
    [4,5,6,7]],
])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [14]:
#show array dimension
print(array_example.ndim)
#show array total element
print(array_example.size)
#show array total element
print(array_example.shape)

3
24
(3, 2, 4)


In [15]:
array_example = np.array(
    [[0,1,2,3],
    [4,5,6,7]],
)
array_example.shape
array_example.ndim
array_example.size

8

In [17]:
a = np.arange(16)
# reshaping an array
b = a.reshape(16,1)
b

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [18]:
display(a)

#add a dimension to an existing array
a2 = a[np.newaxis]
display(a2)
a3 = a2[np.newaxis]
display(a3)

row_vector = a[:,np.newaxis]
row_vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [21]:
a = np.arange(5)
display(a)
display(a.shape)

#expanding dimension
b = np.expand_dims(a, axis=0)
display(b)
display(b.shape)

array([0, 1, 2, 3, 4])

(5,)

array([[0, 1, 2, 3, 4]])

(1, 5)

In [22]:
a

array([0, 1, 2, 3, 4])

In [26]:
# slicing array by index
print(a[2])
print(a[:3])
print(a[::-1])
print(a[-2:])

2
[0 1 2]
[4 3 2 1 0]
[3 4]


In [27]:
array_example

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [28]:
#slicing array with condition
array_example[array_example >= 5]

array([5, 6, 7])

In [29]:
five_up = (array_example >= 5)
array_example[five_up]

array([5, 6, 7])

In [30]:
array_example[array_example%2==0]

array([0, 2, 4, 6])

In [32]:
#sliciing using and
array_example[(array_example%2==0) & (array_example > 3)]
# slicing using or
array_example[(array_example%2==0) | (array_example > 3)]

array([0, 2, 4, 5, 6, 7])

In [34]:
a = np.arange(1,11)
b = a[3:8]
b

array([4, 5, 6, 7, 8])

In [39]:
a1 = np.array(
   [   [0,1,],
       [4,5,]])
a2 = np.array(
   [   [2,3,],
       [6,7,]])

In [40]:
# stacking vertically
np.vstack((a1, a2))

array([[0, 1],
       [4, 5],
       [2, 3],
       [6, 7]])

In [42]:
# stacking horizontally
np.hstack((a1, a2))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
display(a)
a2 = a[np.newaxis]
a4 = np.vstack((a2,a2))
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [45]:
# splitting array horizontally
np.hsplit(a4, 5)

[array([[1, 2],
        [1, 2]]),
 array([[3, 4],
        [3, 4]]),
 array([[5, 6],
        [5, 6]]),
 array([[7, 8],
        [7, 8]]),
 array([[ 9, 10],
        [ 9, 10]])]

In [46]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
a = np.arange(3)
b = np.arange(4,7)
print(a)
print(b)

# basic array operations
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[0 1 2]
[4 5 6]
[4 6 8]
[-4 -4 -4]
[ 0  5 12]
[0.         0.2        0.33333333]


In [51]:
a3

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [52]:
a3.sum()

120

In [53]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
# sum with axis
print(c.sum(axis = 0))
print(c.sum(axis = 1))

[15 18 21 24]
[10 26 42]


In [55]:
print(a)
print(a * 1.6)

[0 1 2]
[0.  1.6 3.2]


In [56]:
# error
z = np.array([1,2, 'z'])
z*15

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [57]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
print(c.min())
print(c.max())
print(c.sum())
print(c.std())
print(c.min(axis = 1))
print(c.max(axis = 0))

1
12
78
3.452052529534663
[1 5 9]
[ 9 10 11 12]


In [59]:
# making matrix
z = np.zeros((6,2))
o = np.ones((6,2))
r = np.random.random((6,2))
print(z)
print(o)
print(r)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0.30369875 0.24939158]
 [0.97392002 0.77386608]
 [0.94216136 0.76794456]
 [0.13600762 0.90458189]
 [0.61327069 0.92618405]
 [0.73475949 0.43303833]]


In [60]:
r + o

array([[1.30369875, 1.24939158],
       [1.97392002, 1.77386608],
       [1.94216136, 1.76794456],
       [1.13600762, 1.90458189],
       [1.61327069, 1.92618405],
       [1.73475949, 1.43303833]])

In [62]:
a1 = np.array([[0,1],[4,5],[7,8]])
print(a1)
a2 = np.array([[0,1,2],[4,5,6]])
print(a2)

[[0 1]
 [4 5]
 [7 8]]
[[0 1 2]
 [4 5 6]]


In [63]:
np.dot(a1, a2)

array([[ 4,  5,  6],
       [20, 29, 38],
       [32, 47, 62]])

In [65]:
# slicing matrix
a1 = np.array([[1,2],[3,4],[5,6]])
print(a1)
print(a1[0])
print(a1[2])
print(a1[0:2])
print(a1[0,1])
print(a1[0][1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[5 6]
[[1 2]
 [3 4]]
2
2


In [68]:
# transforming shape
display(a1)
print(a1.shape)
print(a1.T)
print(a1.T.shape)

array([[1, 2],
       [3, 4],
       [5, 6]])

(3, 2)
[[1 3 5]
 [2 4 6]]
(2, 3)


In [69]:
a = np.arange(6)

In [72]:
a2 = a[np.newaxis]
a2.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [74]:
a3 = a2.reshape(-1,3)
a3

array([[0, 1, 2],
       [3, 4, 5]])

In [76]:
# flatten multidimension array into ID array
a4 = a3.flatten()
print(a4)
print(np.delete(a4, 1))
print(a3)

[0 1 2 3 4 5]
[0 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [79]:
a4 = a3.ravel()
print(a4)
print(np.delete(a4, 1))
print(a3)

[0 1 2 3 4 5]
[0 2 3 4 5]
[[0 1 2]
 [3 4 5]]
